name: Build Executables

# Trigger on tags like v1.0.0-release
on:
  push:
    tags:
      - 'v*-release'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x64, x86]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: ${{ matrix.arch }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-dev

      - name: Build executable
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            pyinstaller --clean --onefile --windowed --icon=app/resources/favicon.ico --add-data "app/resources/*;app/resources" --name Anorm main.py
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            pyinstaller --clean --onefile --windowed --icon=app/resources/favicon.icns --add-data "app/resources/*;app/resources" --name Anorm main.py
          else
            pyinstaller --clean --onefile --windowed --icon=app/resources/favicon.png --add-data ""app/resources/*;app/resources" --name Anorm main.py
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ${{ matrix.os == 'macos-latest' && 'dist/AudioNormalizer.app' || 'dist/AudioNormalizer*' }}